### ISSUE TITLE
Unclaimed Device

### ISSUE THREAD

**Issue by ZaninAndrea** [IglooCloud/IglooBering#80]
### Todo
- [x] unclaimDevice mutation
- [x] deleting environment should unclaim all the devices
- [x] Refactor unclaimed devices
- [x] QR code regeneration
- [x] Add claimed parameter to devices created by business accounts

### unclaimDevice mutation
After being unclaimed, devices should lose all of their data. It should return QR code, id, and token.

### UnclaimedValue
Developers should be able to add unclaimedValues to unclaimedDevices and when the device gets claimed of its values should get claimed as well. The value property of an unclaimedValue should not be settable and should default to null. All of the expenses of an unclaimedValue are billed to the business account that created it.

**Comment by ZaninAndrea** [comment]
### Idea
Unclaimed devices should be normal devices without an environment associated, claiming a device means attaching it to an environment.

Every device will have a producer field, while the device is unclaimed it can execute requests and those will be billed to the producer. When claimed the device will bill the owner of the environment or the producer depending on a setting specified by the producer at creation. 

A `producerHasAccess` setting specifies whether the user specified by `producerId` has access to the device (e.g. for debugging or updating the firmware)

New fields:
- `producerIsBilled`
- `producerHasAccess`
- `producerId`

@SamueleDassatti

**Comment by SamueleDassatti** [comment]
Should users be allowed to change the `producerHasAccess` prop?

**Comment by ZaninAndrea** [comment]
I think they shouldn't, because producers could rely on that to provide integration with other services, analytics and such that may also be critical to the correct working of the device
